apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal-ca
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca-cert
  namespace: default
spec:
  secretName: internal-ca-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations: ["Cell-Arch"]
  isCA: true
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
